"""add_bot_action_logs_table

Revision ID: 80b50a8f0b69
Revises: e72e5017bbd6
Create Date: 2026-06-03 10:22:24.068418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b50a8f0b69'
down_revision: Union[str, Sequence[str], None] = 'e72e5017bbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('trigger_source', sa.String(), nullable=False),
    sa.Column('tx_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_action_logs_id'), 'bot_action_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_action_logs_id'), table_name='bot_action_logs')
    op.drop_table('bot_action_logs')
    # ### end Alembic commands ###
